### ISSUE TITLE
SSO & SAML Credentials Are Sent Unencrypted

### ISSUE THREAD

**Issue by ducarrozb** [nextcloud/user_saml#552]
### Problem
When sending shibboleth login credentials, browser sends data unencrypted, but login works.
What am I missing?

### Steps to reproduce
- Install Nextcloud docker container (find my docker-compose.xml and nginx.conf below)
- SSL Certificates are ok and installed
- Add and enable SSO & SAML authentication
- Configure "Use SAML auth for the Nextcloud desktop clients" for SWITCH SP (https://www.switch.ch/aai/guides/sp/)

### Expected behaviour
- All credentials should be sent encrypted

### Actual behaviour
- Credentials are not sent encrypted. 

#### Browser log: 
see print-screens in the following post:
https://help.nextcloud.com/t/docker-installation-sso-saml-authentication-outputs-metadata-as-http-and-not-as-https/124898

### Server configuration
**Operating system**: Ubuntu 20.04 LTS
**Nextcloud version:** 22.2.0
**List of activated apps:** SSO & SAML authentication 4.1.1

### docker-compose.yml
```
version: '3.9'

volumes:
  nextcloud:
    name: nextcloud
  nextcloud-mariadb:
    name: nextcloud-mariadb

services:
  nginx-proxy:
    restart: always
    environment:
      - TZ=Europe/Zurich
    image: jwilder/nginx-proxy:alpine
    container_name: nextcloud-reverse-proxy
    ports:
      - "8001:443"
    dns_search:
      - "myhost.ch"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - /volume/config/certs/diuf:/etc/nginx/certs:ro
      - /volume/config/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /volume/config/reverse-proxy/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
      - /volume/config/nextcloud/logfiles/error.log:/var/log/nginx/error.log

  php8.0.8-apache:
    restart: always
    image: php:8.0.8-apache
    container_name: nextcloud-php8.0.8-apache
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /volume/usrdata:/var/www/html/

  nextcloud-mariadb:
    image: mariadb
    container_name: nextcloud-mariadb-3306
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    links:
      - nginx-proxy
    volumes:
      - /volume/usrdata/nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_PASSWORD=mypass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=Europe/Zurich
  app:
    image: nextcloud
    restart: always
    container_name: nextcloud
    links:
      - nextcloud-mariadb
      - nginx-proxy
    volumes:
      - /volume/usrdata/nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=myhost.ch
      - MYSQL_PASSWORD=mypass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-mariadb
      - TZ=Europe/Zurich 
```
### ngingx.conf

```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  10240;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  ' -  [] "" '
                      '  "" '
                      '"" ""';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;
    server_tokens off;
    proxy_set_header Proxy "";
    include /etc/nginx/conf.d/*.conf;

    #  nextcloud 
       server {
        listen 8001 ssl http2;
        listen [::]:8001 ssl http2;
        ssl_certificate /etc/nginx/certs/myhost.crt;
        ssl_certificate_key /etc/nginx/certs/myhost.key;
        return 301 https://myhost.ch:8001;
    }

}
daemon off;
```

### config.php
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'xxxxxxxxx',
  'passwordsalt' => 'xxxxxxx',
  'secret' => 'xxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'myhost.ch',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '22.2.0.2',
  'overwrite.cli.url' => 'https://myhost.ch:8001',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-mariadb',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'mypass',
  'installed' => true,
);

```

The logfile in /volume/usrdata/nextcloud/data/nextcloud.log is extremely long, unclear and illegible,  it would make this post cluttered

**Comment by ducarrozb** [comment]
> From a SAML perspective `entityID` can be any type of `URI` (`URN`/`URL`), it's the `AssertionConsumerService` `Location` in the metadata that will need to be `https`

Thank you a lot for your response! In my case, the `AssertionConsumerService` is http. How can I change this in my configuration?

**Comment by jgallucci32** [comment]
I am also looking for the same information. The entire site is `https` and deployed using the official helm chart. But the SSO & SAML plugin does not seem to honor the server URL being secure. The `AssertionConsumerService` is http causing issues when integrating with Keycloak.

**Comment by ducarrozb** [comment]
Can you please write down your entire docker-compose.yml?
I have the nextcloud section below `volumes: ` but this way I get the following error:
```
ERROR: The Compose file '/volume/config/nextcloud/docker-compose.yml' is invalid because:
volumes.nextcloud value 'extraEnv' does not match any of the regexes: '^x-'
```

```
volumes:
  nextcloud:
    name: nextcloud
    extraEnv:
     - name: OVERWRITEPROTOCOL
       value: "https"
  nextcloud-mariadb:
    name: nextcloud-mariadb
```

I'm quite new to docker, how do I have to insert your setting into my docker-compose.yml?
