### ISSUE TITLE
Multiple IDP broken since 5.0.2

### ISSUE THREAD

**Issue by fhatz** [nextcloud/user_saml#630]
After updating to 5.0.2 only first idp is allways selected, selection of second, third... endpoints is not working. Most porobably this is in relation to the latest change, allways setting idp=1 by default

**Comment by cmitasch** [comment]
I can confirm that issue with Nextcloud 24.0.2.
Downgrading the app to 5.0.1 resolves the issue.

**Comment by brunt82** [comment]
I can also confirm that the login by SAML to MS Azure does not work with version 5.0.2 (NC = 24.0.2). Here the log output which orrurs when I try it:

`{"reqId":"h9UXc9Ah3BCbjwhP3BE3","level":3,"time":"2022-06-23T12:13:20+02:00","remoteAddr":"194.95.99.41","user":"--","app":"index","method":"GET","url":"/apps/user_saml/saml/login?originalUrl=&requesttoken=****token-removed****&idp=2","message":"Invalid array settings: idp_entityId_not_found, idp_sso_not_found, idp_cert_or_fingerprint_not_found_and_required","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0","version":"24.0.2.1","exception":{"Exception":"OneLogin\\Saml2\\Error","Message":"Invalid array settings: idp_entityId_not_found, idp_sso_not_found, idp_cert_or_fingerprint_not_found_and_required","Code":2,"Trace":[{"file":"/var/www/nextcloud/apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php","line":177,"function":"__construct","class":"OneLogin\\Saml2\\Settings","type":"->","args":[[true,false,"https://nextcloud-test.domain.local/apps/user_saml/saml",[false,false,false,false,false,"And 9 more entries, set log level to debug to see all entries"],["https://nextcloud-test.domain.local/apps/user_saml/saml/metadata",["https://nextcloud-test.domain.local/apps/user_saml/saml/acs"],"urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified","",""],"And 1 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/nextcloud/apps/user_saml/lib/Controller/SAMLController.php","line":174,"function":"__construct","class":"OneLogin\\Saml2\\Auth","type":"->","args":[[true,false,"https://nextcloud-test.domain.local/apps/user_saml/saml",[false,false,false,false,false,"And 9 more entries, set log level to debug to see all entries"],["https://nextcloud-test.domain.local/apps/user_saml/saml/metadata",["https://nextcloud-test.domain.local/apps/user_saml/saml/acs"],"urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified","",""],"And 1 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"login","class":"OCA\\User_SAML\\Controller\\SAMLController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\User_SAML\\Controller\\SAMLController"},"login"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\User_SAML\\Controller\\SAMLController"},"login"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\User_SAML\\Controller\\SAMLController","login",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["*** sensitive parameters replaced ***","user_saml.SAML.login"]]},{"file":"/var/www/nextcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/user_saml/saml/login"]},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Settings.php","Line":141,"CustomMessage":"--"}}
`
Downgrading to 5.0.1 helps.

**Comment by KoffeinKaio** [comment]
Mh thats weird. This is exactly what my last PR was fixing.
An explanation is that downgrading to 5.0.1 helps, as it creates exactly this bug with only one IDP.
So that should be related to having multiple IDPs. 

Could you post occ saml:config:get and/or screenshots showing your settings?

I'll try to debug it when I find the time.

**Comment by apw1388** [comment]
The same problem appears on NC 22.2.9 and user_saml 5.0.2

Here is the config without the certificates and keys:

```
  - 1:
    - general-idp0_display_name: B2ACCESS
    - general-uid_mapping: unity:persistent
    - idp-entityId: https://b2access.eudat.eu:8443/saml-idp/metadata
    - idp-singleLogoutService.url: https://b2access.eudat.eu/saml-idp/SLO-WEB
    - idp-singleSignOnService.url: https://b2access.eudat.eu/saml-idp/saml2idp-web
    - idp-x509cert: -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
    - saml-attribute-mapping-displayName_mapping: urn:oid:2.5.4.3
    - saml-attribute-mapping-email_mapping: urn:oid:0.9.2342.19200300.100.1.3
    - security-authnRequestsSigned: 1
    - security-logoutRequestSigned: 1
    - security-logoutResponseSigned: 1
    - security-nameIdEncrypted: 1
    - security-signMetadata: 1
    - security-wantAssertionsSigned: 1
    - security-wantNameId: 1
    - security-wantXMLValidation: 1
    - sp-privateKey: -----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
    - sp-x509cert: -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
  - 2:
    - general-idp0_display_name: unity test
    - general-uid_mapping: urn:oid:1.3.6.1.4.1.5923.1.1.1.13
    - idp-entityId: https://zam10163.zam.kfa-juelich.de/saml-idp/metadata
    - idp-singleLogoutService.url: https://zam10163.zam.kfa-juelich.de/saml-idp/SLO-WEB
    - idp-singleSignOnService.url: https://zam10163.zam.kfa-juelich.de/saml-idp/saml2idp-web
    - idp-x509cert: -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
    - saml-attribute-mapping-displayName_mapping: urn:oid:2.5.4.3
    - saml-attribute-mapping-email_mapping: urn:oid:0.9.2342.19200300.100.1.3
    - security-authnRequestsSigned: 1
    - security-logoutRequestSigned: 1
    - security-logoutResponseSigned: 1
    - security-nameIdEncrypted: 1
    - security-signMetadata: 1
    - security-wantAssertionsSigned: 1
    - security-wantNameId: 1
    - security-wantXMLValidation: 1
    - sp-name-id-format: urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
    - sp-privateKey: -----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
    - sp-x509cert: -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
  - 3:
    - general-idp0_display_name: Helmholtz dev AAI
    - general-uid_mapping: urn:oid:1.3.6.1.4.1.5923.1.1.1.13
    - idp-entityId: https://login-dev.helmholtz.de/saml-idp/metadata
    - idp-singleLogoutService.url: https://login-dev.helmholtz.de/saml-idp/SLO-WEB
    - idp-singleSignOnService.url: https://login-dev.helmholtz.de/saml-idp/saml2idp-web
    - idp-x509cert: -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
    - saml-attribute-mapping-displayName_mapping: urn:oid:2.5.4.3
    - saml-attribute-mapping-email_mapping: urn:oid:0.9.2342.19200300.100.1.3
    - saml-attribute-mapping-group_mapping: urn:oid:1.3.6.1.4.1.5923.1.1.1.7
    - security-authnRequestsSigned: 1
    - security-logoutRequestSigned: 1
    - security-logoutResponseSigned: 1
    - security-signMetadata: 1
    - security-wantAssertionsSigned: 1
    - security-wantNameId: 1
    - security-wantXMLValidation: 1
    - sp-privateKey: -----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
    - sp-x509cert: -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```
